updating engine files: db_storage and file_storage
arvicrin/AirBnB_clone_v3 pull request #1
Opened 2020-04-28 23:06 UTC by oscarmrt

updating engine files: db_storage and file_storage working with def get(self, cls, id) and def count(self, cls=None).

2020-04-28 23:16 UTC, arturovictoriar requested changes

2020-04-28 23:16 UTC, arvicrin commented on models/engine/file_storage.py
> +        else:
This "else" can be skip

2020-04-28 23:16 UTC, arvicrin commented on models/engine/file_storage.py
> +        else:
This "else" can be skip

2020-04-28 23:16 UTC, arvicrin commented on models/engine/db_storage.py
> +        else:
This "else" can be skip

2020-04-28 23:16 UTC, arvicrin commented on models/engine/db_storage.py
> +        else:
This "else" can be skip

2020-04-28 23:29 UTC, arturovictoriar approved these changes
It is OK to update the master

2020-04-28 23:30 UTC, oscarmrt commented
Ok. Thank you.

2020-04-28 23:34 UTC, arvicrin commented
You are missing the test cases, so you need to add them before i merge the request.

2020-04-29 00:34 UTC, arturovictoriar approved these changes

2020-04-29 00:35 UTC, merged